// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPI_Weather_Browser;

#nullable disable

namespace ASP.NET_MinimalAPI_Weather_Browser.Migrations
{
    [DbContext(typeof(WeatherEntityDB))]
    partial class WeatherEntityDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MinimalAPI_Weather_Browser.Weather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cloudiness")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Temperature")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Wind")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Weathers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0507bdf-6038-4cc4-82ff-765e726adf9b"),
                            Cloudiness = "misty",
                            Icon = "🌦",
                            Location = "Davidson County",
                            Temperature = "35 °C",
                            Wind = "70 km/h"
                        },
                        new
                        {
                            Id = new Guid("1abb312a-e5d8-4ff0-afa5-61fc8679de10"),
                            Cloudiness = "cloudy",
                            Icon = "🌞",
                            Location = "Canton",
                            Temperature = "31 °C",
                            Wind = "62 km/h"
                        },
                        new
                        {
                            Id = new Guid("88e047e6-44ad-488b-885f-8ed1723bbc7d"),
                            Cloudiness = "clear",
                            Icon = "🌞",
                            Location = "Duluth",
                            Temperature = "17 °C",
                            Wind = "83 km/h"
                        },
                        new
                        {
                            Id = new Guid("c5671b48-78d4-432a-bc4c-08835d738c4c"),
                            Cloudiness = "misty",
                            Icon = "⚡",
                            Location = "El Paso",
                            Temperature = "14 °C",
                            Wind = "57 km/h"
                        },
                        new
                        {
                            Id = new Guid("f162346c-0c67-4bc0-adc2-3c5f47f2fd7b"),
                            Cloudiness = "clear",
                            Icon = "❄",
                            Location = "Burlington",
                            Temperature = "3 °C",
                            Wind = "39 km/h"
                        },
                        new
                        {
                            Id = new Guid("7ddb8956-a48b-4f9c-9fc1-a4b895004abe"),
                            Cloudiness = "sunny",
                            Icon = "❄",
                            Location = "Duluth",
                            Temperature = "-9 °C",
                            Wind = "72 km/h"
                        },
                        new
                        {
                            Id = new Guid("ea01290c-938c-41b8-a661-777ac7f463d9"),
                            Cloudiness = "sunny",
                            Icon = "☀",
                            Location = "Cleveland",
                            Temperature = "17 °C",
                            Wind = "67 km/h"
                        },
                        new
                        {
                            Id = new Guid("9b8ce014-efaf-4b97-a2ed-adbe2b6212ac"),
                            Cloudiness = "sunny",
                            Icon = "🌤",
                            Location = "Brownsville",
                            Temperature = "3 °C",
                            Wind = "67 km/h"
                        },
                        new
                        {
                            Id = new Guid("9138b511-741f-4e75-af2e-b85f0b4c3afd"),
                            Cloudiness = "misty",
                            Icon = "🌤",
                            Location = "Detroit",
                            Temperature = "-7 °C",
                            Wind = "6 km/h"
                        },
                        new
                        {
                            Id = new Guid("c570e7f2-6ac0-4f60-801e-b27d2cce2042"),
                            Cloudiness = "clear",
                            Icon = "❄",
                            Location = "Clearwater",
                            Temperature = "11 °C",
                            Wind = "38 km/h"
                        },
                        new
                        {
                            Id = new Guid("54c802dc-4839-4f9c-9e2b-8dbc01612777"),
                            Cloudiness = "clear",
                            Icon = "🌤",
                            Location = "Cleveland",
                            Temperature = "18 °C",
                            Wind = "72 km/h"
                        },
                        new
                        {
                            Id = new Guid("49063ce9-3d21-4091-a48d-cec53f3ed7ad"),
                            Cloudiness = "snowy",
                            Icon = "🌞",
                            Location = "Downey",
                            Temperature = "24 °C",
                            Wind = "86 km/h"
                        },
                        new
                        {
                            Id = new Guid("ba0052eb-6a86-4afb-8e6f-98f0503f968b"),
                            Cloudiness = "misty",
                            Icon = "❄",
                            Location = "Fontana",
                            Temperature = "-17 °C",
                            Wind = "71 km/h"
                        },
                        new
                        {
                            Id = new Guid("6ab3de29-8b45-4af7-861c-74e2d36cc099"),
                            Cloudiness = "misty",
                            Icon = "🌦",
                            Location = "Erie",
                            Temperature = "29 °C",
                            Wind = "20 km/h"
                        },
                        new
                        {
                            Id = new Guid("d1b4e2b9-cdd5-4b39-ab43-5444a6e7917a"),
                            Cloudiness = "misty",
                            Icon = "☀",
                            Location = "Denver",
                            Temperature = "29 °C",
                            Wind = "29 km/h"
                        },
                        new
                        {
                            Id = new Guid("da93a53a-4188-49cd-9657-9a7bb85db29c"),
                            Cloudiness = "snowy",
                            Icon = "⛅",
                            Location = "Davidson County",
                            Temperature = "20 °C",
                            Wind = "50 km/h"
                        },
                        new
                        {
                            Id = new Guid("e375dfc6-83ec-4155-b204-5eb8d7c510c9"),
                            Cloudiness = "snowy",
                            Icon = "❄",
                            Location = "Davenport",
                            Temperature = "33 °C",
                            Wind = "67 km/h"
                        },
                        new
                        {
                            Id = new Guid("35269833-2e61-4425-afdd-a68e1180ee28"),
                            Cloudiness = "clear",
                            Icon = "☀",
                            Location = "Garden Grove",
                            Temperature = "-10 °C",
                            Wind = "88 km/h"
                        },
                        new
                        {
                            Id = new Guid("20d58d9f-8271-4334-8bd5-b30e967f11af"),
                            Cloudiness = "misty",
                            Icon = "🌦",
                            Location = "Champaign",
                            Temperature = "-2 °C",
                            Wind = "81 km/h"
                        },
                        new
                        {
                            Id = new Guid("45253e5e-0cf4-4b64-81ef-a7f67ca7e344"),
                            Cloudiness = "misty",
                            Icon = "🌦",
                            Location = "Gainesville",
                            Temperature = "-19 °C",
                            Wind = "96 km/h"
                        },
                        new
                        {
                            Id = new Guid("28b43bde-83d2-40ec-b370-6a5414055683"),
                            Cloudiness = "snowy",
                            Icon = "🌞",
                            Location = "Fairfield",
                            Temperature = "30 °C",
                            Wind = "60 km/h"
                        },
                        new
                        {
                            Id = new Guid("5e45da53-5d97-47dc-acf0-7cc47a650a35"),
                            Cloudiness = "sunny",
                            Icon = "❄",
                            Location = "Daytona Beach",
                            Temperature = "26 °C",
                            Wind = "90 km/h"
                        },
                        new
                        {
                            Id = new Guid("5e53e276-f1d9-4a4e-8e9a-fc841d862d3f"),
                            Cloudiness = "clear",
                            Icon = "❄",
                            Location = "Danbury",
                            Temperature = "-9 °C",
                            Wind = "82 km/h"
                        },
                        new
                        {
                            Id = new Guid("fc10b0d3-3206-48a5-a4e8-41f33d352dac"),
                            Cloudiness = "sunny",
                            Icon = "🌦",
                            Location = "Fitchburg",
                            Temperature = "27 °C",
                            Wind = "76 km/h"
                        },
                        new
                        {
                            Id = new Guid("7bfd79e4-4dcf-4ec4-aa12-7f9d6c74b369"),
                            Cloudiness = "sunny",
                            Icon = "❄",
                            Location = "Charleston",
                            Temperature = "-12 °C",
                            Wind = "26 km/h"
                        },
                        new
                        {
                            Id = new Guid("93a7bf52-4a4f-4a79-9021-7b1ef0504a56"),
                            Cloudiness = "misty",
                            Icon = "☀",
                            Location = "Escondido",
                            Temperature = "-3 °C",
                            Wind = "39 km/h"
                        },
                        new
                        {
                            Id = new Guid("b434a409-5235-45ea-9409-efef8c5cade0"),
                            Cloudiness = "sunny",
                            Icon = "🌤",
                            Location = "Chicago",
                            Temperature = "32 °C",
                            Wind = "29 km/h"
                        },
                        new
                        {
                            Id = new Guid("cf240d06-05a7-46e8-89fa-8a9384168e57"),
                            Cloudiness = "snowy",
                            Icon = "☀",
                            Location = "Fargo",
                            Temperature = "-5 °C",
                            Wind = "38 km/h"
                        },
                        new
                        {
                            Id = new Guid("76760cb7-f78b-4e4b-9b34-55356c9a14a3"),
                            Cloudiness = "cloudy",
                            Icon = "🌤",
                            Location = "Daytona Beach",
                            Temperature = "12 °C",
                            Wind = "68 km/h"
                        },
                        new
                        {
                            Id = new Guid("9a0bf0f9-fd1c-4d60-a95c-214065b61d63"),
                            Cloudiness = "sunny",
                            Icon = "❄",
                            Location = "Fitchburg",
                            Temperature = "-15 °C",
                            Wind = "50 km/h"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
